### ISSUE TITLE
Something go wrong

### ISSUE THREAD

**Issue by japochino** [danielneis/moodle-mod_webrtcexperiments#1]
I have installed the plugin in my moodle 2.8

When I access, there is no way to write the session name. So I select a kind of session, a direction and click on new session button.

But when I access from another browser to test the video call, I don't see nothing for joining the session before created.

How does this plugin work? When accessing https://www.webrtc-experiment.com/RTCMultiConnection/all-in-one.html I have a textfield for writing the session name and when I access from another brower I can see the session created and join it.

Another question, Is it possible to translate the plugin when changing the language selected?

Thanks!

**Comment by danielneis** [comment]
Hello,

when you click the new session button, a session is created with a default name,
I've changed it because there are plans to implement an automatic-join feature
for the following users.
When there is a session created, if you acces the module and wait about 3 seconds,
a new button to join the session should appear.
Did you wait that long?
 Also, have you tried to use the network and javascript console tools available on firefox and/or firebug to see if there are any errors being reported?

Kind regards,
Daniel

**Comment by japochino** [comment]
Hello Daniel

Exactly, I wait enough time, but I'm getting the following error in the browser console:

```
WebSocket connection to 'wss://novoaeon.com.br:12034/' failed: WebSocket opening handshake was canceled
Signaling channel is ready.
```

**Comment by japochino** [comment]
Any idea?

Thanks!

**Comment by danielneis** [comment]
Hello, I still didn't look closely to this.
Which browser and version are you using? Linux, Mac, BSD, Windows, other?
Are you behind a firewall that does not allow you to use port 12034?

**Comment by japochino** [comment]
Hello

I'm using Chrome version 43.0.2357.130 m, Linux and I'm not behind any firewall that does not allow to use port 12034

Any suggestions?

**Comment by japochino** [comment]
Also tested in Firefox but didn't work

**Comment by danielneis** [comment]
Hello,

are you using the same browser window in different tabs to test the plugin?
It may be an issue, when on same computer i've just tested using a "private window" or "incognito window" (or whatever you browser calls it), or different browsers.

also, i guess you are using the latest master version...

**Comment by japochino** [comment]
No I'm not. I'm using differents computers.

Also, I'm using the lastest version.

Any more ideas?

**Comment by danielneis** [comment]
Can you test with a live version at the link below?
http://www.moodlebrasil.org/mod/webrtcexperiments/view.php?id=78

**Comment by danielneis** [comment]
the websocket server at novoaeon.com.br is offline, you may trying using your own websocket server.

**Comment by ayhan01** [comment]
I have that same problem.
I installed seamlessly plugin. (Moodle 2,9)
I tested with two separate computer.
I'm launching a new channel notified by the computer. Video channel is opened. But I can not see when I open the video channel from the second computer. Off the firewall on computers. I use Firefox.

**Comment by danielneis** [comment]
Hello,

the signaling server was offline for sometime but now it is online again.

The only change is on server port that now is 1234 and not 12034 (note that the new one to use does not have the zero on center).

I've made a new version available here on github that changes the defaults, but the activities already added must be changed editing the instance configuration.

Coud you please test with this port and see if it works?

Also, it it does not work, it would be important to have the logs from your browser's console.

Kind regards,
Daniel

**Comment by ayhan01** [comment]
It is okay. Now it works. Thank you. 
But there are problems in image and sound. Sometimes no sound, sometimes the video freezes.
I also have some questions.
1-Signal server service will be paid in the future for me?
2-How can we define different signal server. What's different signaling server names?
3-WebRTC is if we work in Moodle been working in video rental server and increases the sound quality?

**Comment by danielneis** [comment]
Hello, good to know it is working =)

About your questions:
1. No, it is free and always will be. Altough I would recommend you to setup your own following the instructions at https://github.com/muaz-khan/WebRTC-Experiment/tree/master/websocket-over-nodejs
2. You can change the signaling server that is used on the module settings page. If you want to know more about signaling, please take a look at https://github.com/muaz-khan/WebRTC-Experiment/blob/master/Signaling.md  and http://www.html5rocks.com/en/tutorials/webrtc/infrastructure/
3. Don't know which software you're using but WebRTC is not supposed to "increase sound quality" it is "just" a way to communicate using browsers and binary data channels.

Kind regards,
Daniel
