### ISSUE TITLE
Missing string from webrtcexperiments.php file

### ISSUE THREAD

**Issue by drachels** [danielneis/moodle-mod_webrtcexperiments#3]
Hi Daniel,
When you are in a WebRTCExperiments activity and click on permissions with debugging on, you get a warning message about a possible missing string. The following sting needs to be added to the .../webrtcexperiments/lang/en/webrtcexperiments.php file:

$string['webrtcexperiments:view'] = 'Can view';

**Comment by danielneis** [comment]
ok, thank you very much.
